brew cask install 1password
brew cask install adium
brew cask install bartender
brew cask install cleanmymac
brew cask install cloud
brew cask install dropbox
brew cask install firefox
brew cask install flux
brew cask install google-chrome
brew cask install iterm2
brew cask install launchbar
brew cask install macvim
brew cask install moneydance
brew cask install rubymine
brew cask install slack
brew cask install skype
brew cask install spotify
brew cask install textexpander
brew cask install viber
