[tools]
argocd = "3.2.2"
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gcloud = "527.0.0"
github-cli = "latest"
helm = "3.11.1"
java = "adoptopenjdk-11.0.25+9"
k9s = "latest"
kubectl = "1.31.8"
kubectx = "latest"
kustomize = "5.0.1"
lazygit = "latest"
mysql = "8.0.31"
neovim = "latest"
node = "24.5.0"
postgres = "14.18"
python = "3.12"
redis-cli = "latest"
ripgrep = "latest"
ruby = "3.1.1"
sshuttle = "latest"
stern = "latest"
vault = "1.13.12"
yq = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = []
