[tools]
argocd = "3.0.6"
bat = "latest"
eza = "latest"
fzf = "latest"
gcloud = "527.0.0"
github-cli = "latest"
helm = "3.11.1"
java = "adoptopenjdk-11.0.25+9"
k9s = "latest"
kubectl = "1.31.8"
kubectx = "latest"
kustomize = "5.0.1"
lazygit = "latest"
mysql = "8.0.31"
neovim = "latest"
node = "16.6.1"
python = "3.11.3"
ripgrep = "latest"
sshuttle = "latest"
vault = "1.13.12"
zoxide = "latest"
